project_emp/homework_login/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include('loginapp.urls'))
]

project_emp/loginapp/urls.py
from django.urls import path

from loginapp import views


app_name="loginapp"
urlpatterns=[
    path('regist/',views.regist,name='regist'),
    path('user/',views.user,name='user'),
    path('registlogic/',views.registlogic,name='registlogic'),
    path('captcha/',views.getcaptcha,name='getcaptcha'),
    path('captchalogic/',views.captchalogic,name='captchalogic'),
    path('login/',views.login,name='login'),
    path('loginlogic/',views.loginlogic,name='loginlogic'),
    path('logincheck/',views.logincheck,name='logincheck'),
    path('emplist/',views.emplist,name='emplist'),
    path('check/',views.check,name='check'),
    path('checkname/',views.checkname,name='checkname'),
    path('addemp/',views.addemp,name='addemp'),
    path('addlogic/',views.addlogic,name='addlogic'),
    path('delete/',views.delete,name='delete'),
    path('updateemp/',views.updateemp,name='updateemp'),
    path('updalogic/',views.updalogic,name='updalogic'),

]

project_emp/loginapp/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    user=models.CharField(max_length=20)
    name=models.CharField(max_length=20)
    password=models.CharField(max_length=20)
    sex=models.CharField(max_length=1)

    class Meta:
        db_table='User'


class Employee(models.Model):
    name=models.CharField(max_length=20)
    salary=models.DecimalField(max_digits=7,decimal_places=2)
    age = models.IntegerField()
    pic = models.ImageField(upload_to='pics')

    class Meta:
        db_table='Employee'

project_emp/loginapp/views.py
from django.core.paginator import Paginator
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect
from loginapp.models import User,Employee
import random,string
from loginapp.captcha.image import ImageCaptcha
import uuid,os,json
# Create your views here.

#进入注册页面
def regist(request):
    msg=request.POST.get('msg')
    if msg:
        return render(request,'ems/regist.html',{'msg':msg})
    else:
        return render(request,'ems/regist.html')

def user(request):
    # 获取用户名
    username=request.POST.get('name')
    if len(username)!=0:
        # 数据库中查找
        us = User.objects.filter(user=username)
        if us:
            # 用户名存在
            return HttpResponse('用户名已存在')
        # 用户不存在
        else:
            return HttpResponse("用户名合法")
    else:
        return HttpResponse('用户名不能为空')

# 生成验证码
def getcaptcha(request):
    # 为验证码设置字体，默认获取当前目录下的segoesc.ttf文件
    image=ImageCaptcha()
    # 获取随机码
    #字母大小写+数字，随机抽取5位作为验证码['x','x','x','x','x']
    code=random.sample(string.ascii_letters+string.digits,5)
    #将获得的验证码拼接在一起
    code=''.join(code)
    print(code)
    #将验证码存入session，以备后继判断使用
    request.session['code']=code
    #将生成的随机字符拼接成字符串，作为验证码图片中的文本
    data=image.generate(code)
    #写出验证码图片，给客户端
    return HttpResponse(data,'image/png')

def captchalogic(request):
    # 获取用户输入的验证码
    code = request.POST.get('num')
    # 将存入session的验证码取出
    session_code = request.session.get('code')
    if code.lower() == session_code.lower():
        return HttpResponse('验证码正确')
    else:
        return HttpResponse('验证码不正确')


#进入注册页面，获取用户名、姓名、密码、性别
def registlogic(request):
    # 获取用户名
    username=request.POST.get('name')
    # # 数据库中查找
    us = User.objects.filter(user=username)
    if us:
    #     # 用户名存在
        return redirect('loginapp:regist')
    # # 用户不存在
    else:
        # 获取用户名
        username=request.POST.get('name')
        name = request.POST.get('name')
        password1 = request.POST.get('pwd1')
        password2 = request.POST.get('pwd2')
        sex = request.POST.get('sex')
        # 获取用户输入的验证码
        code = request.POST.get('number')
        # 将存入session的验证码取出
        session_code = request.session.get('code')
        # 进入数据库中查询：用户名是否存在
        # 判断验证码是否输入有误
        if password2==password1:
            if code.lower() == session_code.lower():
                User.objects.create(user=username, name=name, password=password1, sex=sex)
                return redirect('loginapp:login')
            else:
                return redirect('loginapp:login')
        else:

            return redirect('loginapp:regist')


def login(request):
    name=request.COOKIES.get('name')
    password=request.COOKIES.get('password')
    user=User.objects.filter(name=name,password=password)
    if user:
        request.session['flag']='ok'
        return redirect('loginapp:emplist')
    else:
        return render(request,"ems/login.html")

def loginlogic(request):
    name=request.GET.get('name')
    password=request.GET.get('password')
    print(password)
    checkbox=request.GET.get('checkbox')

    res=redirect('loginapp:emplist')
    request.session['flag']='ok'
    if checkbox:
        res.set_cookie('name',name,max_age=600)
        res.set_cookie('password',password,max_age=600)
    return res

def logincheck(request):
    name = request.POST.get('name')
    password = request.POST.get('pwd')
    checkbox = request.POST.get('checkbox')
    user = User.objects.filter(name=name, password=password)
    if user:
        return HttpResponse('成功')

    else:
        return HttpResponse('用户名或密码错误！')





#职工列表
def emplist(request):
    number = request.GET.get('num')

    print(number)
    if number == None:
        number = 1
    # 查询数据库中所有的职工信息,分页
    pagtor = Paginator(Employee.objects.all(), per_page=3)
    page = pagtor.page(number)  # 某一页的page对象
    # #将查询到的职工信息全部显示在浏览器页面上，通过{ }进行传参
    return render(request, 'ems/emplist.html', {'page': page})

def check(request):
    return render(request,'ems/check.html')

def checkname(request):
    def mydefault(u):
        if isinstance(u,Employee):
            return {'id':u.id,'name':u.name,'salary':str(u.salary),'age':u.age,'pic':u.pic.url}

    name=request.GET.get('name')
    print(name)
    users=Employee.objects.filter(name__contains=name)
    print(users)
    # json序列化
    json_str=json.dumps(list(users),default=mydefault)
    print(json_str)
    # return HttpResponse(json_str)
    return JsonResponse({'users':list(users)},json_dumps_params={'default':mydefault})

# 添加员工信息页面
def addemp(request):
    # 获取页面页数
    num=request.GET.get('num')

    return render(request,'ems/addEmp.html',{'num':num})

#创建唯一的文件名
def generateUUID(filename):
    id=str(uuid.uuid4())
    extend=os.path.splitext(filename)[1]
    return id+extend

# 添加员工信息
def addlogic(request):
    # 获取页面页数
    num=request.GET.get('num')

    # 获取新加的员工姓名、薪水、年龄
    name=request.POST.get('name')
    print(name)
    salary=request.POST.get('salary')
    age = request.POST.get('age')

    # 获取头像照片
    file=request.FILES.get('pic')
    # print(file)
    # 调用自定义的generateUUID生成唯一文件名
    # file.name=generateUUID(file.name)
    file.name=generateUUID(file.name)

    # 将员工信息添加到数据库中
    Employee.objects.create(name=name,salary=salary,age=age,pic=file)
    return redirect('/hello/emplist/?num=%s'%(num))



# 删除员工信息
def delete(request):
    num=request.GET.get('num')
    # 获取要删除员工的id
    id=request.GET.get('id')
    # 通过id来删除员工
    Employee.objects.filter(id=id).delete()
    return redirect('/hello/emplist/?num=%s'%(num))

# 更新员工信息页面
def updateemp(request):
    # 获取要修改员工的id来获得员工的信息，最终显示在浏览器上
    num=request.GET.get('num')
    id=request.GET.get('id')
    user=Employee.objects.get(id=id)
    #通过{ }将要修改的员工信息传到更新页面上
    # return render(request,'ems/updateEmp.html',{'id':id,'name':name,'salary':salary,'age':age})
    return render(request,'ems/updateEmp.html',{'user':user,'id':id,'num':num})
# 更新员工信息
def updalogic(request):
    # 获取要修改员工的信息
    num=request.GET.get('num')
    id=request.GET.get('id')
    # 获取头像照片
    file = request.FILES.get('source')
    name=request.POST.get('name')
    salary=request.POST.get('salary')
    age=request.POST.get('age')
    # 通过id查询数据库，获取员工信息并修改保存
    user = Employee.objects.get(id=id)
    if not file:
        user.name=name
        user.age=age
        user.salary=salary
    else:
        # 调用自定义的generateUUID生成唯一文件名
        file.name=generateUUID(file.name)
        user.pic=file
        user.name=name
        user.age=age
        user.salary=salary
    user.save()
    return redirect('/hello/emplist/?num=%s'%(num))

project_emp/templates/ems/addEmp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>add Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css"
			href="/static/css/style.css" />
	</head>


	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="time">

								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">Main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						add Emp info:
					</h1>
{#					<form action="/hello/addlogic/" method="post">#}
					<form action="{% url 'loginapp:addlogic' %}?num={{ num }}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0" class="form_table">
                            <tr>
                                <td>
                                    <input type="file" name="pic">
                                </td>
                                <td>
{#                                    <img src="{% static '' %}" alt="" width="50px" height="50px">#}
                                </td>
                            </tr>
							<tr>
								<td valign="middle" align="right">
									name:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									salary:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									age:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Confirm" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>

 <script type="text/javascript">
    time=document.getElementById('time');
    date=new Date();
    time.innerHTML=date
 </script>

</html>

project_emp/templates/ems/check.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
{% load  static %}
	<head>
		<title>check</title>
        <style>
            a{
                text-decoration:none;
            }


        </style>

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	</head>

    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
{#    <script src=""></script>#}
    <script>
        function check() {
            text=$('#text').val();
            $.ajax({
                type:'get',
                url:"{% url 'loginapp:checkname' %}",
                data:'name='+text,
                success:function (data) {
                    obj = data['users'];
                    var tablelist = "<tr><td>ID</td><td>Name</td><td>Salary</td><td>Age</td><td>Pictur</td></tr>";
                    for (var i = 0; i < obj.length; i++) {
                        id = obj[i]['id'];
                        name = obj[i]['name'];
                        salary = obj[i]['salary'];
                        age = obj[i]['age'];
                        pic = obj[i]['pic'];
                        tablelist += "<tr><td>" + id + "</td><td>" + name + "</td><td>" + salary + "</td><td>" + age + "</td><td>"+ "<img height=50px width=50px src='/static/"+pic+"'>" + "</td></tr>"
                    }
                    table=$('#table');
                    table.html(tablelist)

                }
            })

        }




    </script>



    <script type="text/javascript">
    function check1() {
{#        创建对象#}
        var xhr;
{#        兼容所有浏览器#}
        if (window.ActiveXObject){
            xhr=new ActiveXObject('Microsoft.XMLHTTP')
        }else if(window.XMLHttpRequest){
            xhr=new XMLHttpRequest()
        }
{#        获取输入的文本内容#}
        text=document.getElementById('text').value;
        console.log(text);
{#        判断输入的文本长度#}
        if (text.length==0){
            document.getElementById('table').innerHTML='请输入关键字'
        }else {
            console.log('heheh');
{#            发送请求到服务器#}
            xhr.open('get',"{% url 'loginapp:checkname'%}?name="+text,true);
            xhr.send();
{#            监听接收状态#}
            xhr.onreadystatechange=function () {
                if(xhr.readyState==4 && xhr.status==200){
                obj=eval(xhr.responseText);
                var tablelist="<tr><td>ID</td><td>Name</td><td>Salary</td><td>Age</td><td>Pictur</td></tr>";
                for (var i=0;i<obj.length;i++){
                    id=obj[i]['id'];
                    name=obj[i]['name'];
                    salary=obj[i]['salary'];
                    age=obj[i]['age'];
                    pic=obj[i]['pic'];
                    tablelist+="<tr><td>" + id + "</td><td>" + name + "</td><td>" + salary + "</td><td>" + age + "</td><td>" + pic + "</td></tr>"
                }
                document.getElementById('table').innerHTML=tablelist
                }
            }
        }
    }



    </script>

	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p id="time">

							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						Welcome!
					</h1>

					 <form action="{% url 'loginapp:checkname' %}" method="get" enctype="application/x-www-form-urlencoded">
                         <input type="text" id="text" onkeyup="check()" >
                         <input type="button" value="查询" name="username" onclick="check()">
                         <input type="submit">
                     </form>

                    <table id="table" border="1" cellspacing="0">

					 </table>

					<p>
						<input type="button" class="button" value="Emplist" onclick="location.href='/hello/emplist'"/>
					</p>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>
	</body>
<script>
    date=new Date();
    console.log(date);
    document.getElementById('time').innerHTML=date;

</script>

</html>

project_emp/templates/ems/emplist.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
{% load  static %}
	<head>
		<title>emplist</title>
        <style>
            .a{
                width:20px;
                height: 20px;
                border:1px solid #e1e2e3;
                cursor:pointer;
                display: inline-block;
                text-align: center;
                line-height: 20px;
            }
            .b{
                border:0;
                width:20px;
                height: 20px;
                cursor:pointer;
                display: inline-block;
                text-align: center;
                line-height: 20px;
            }
            a{
                text-decoration:none;
            }
        </style>

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	</head>
    <script>
        function deletedata(id) {
            var msg="您真的确定要删除吗？\n\n请确认！";
            if (confirm(msg)==true)
            {
{#                location.href='/hello/emplist';#}
                location.href="{% url 'loginapp:delete' %}?num={{ page.number }}&id="+id;
                return true
            }else {
                return false;
            }
        }

    </script>




	<body>
		<div id="wrap">
			<div id="top_content"> 
				<div id="header">
					<div id="rightheader">
						<p id="time">

							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						Welcome!
					</h1>
					<table class="table">
						<tr class="table_header">
							<td>
								ID
							</td>
							<td>
								Name
							</td>
							<td>
								Salary
							</td>
							<td>
								Age
							</td>
                            <td>
                                pic
                            </td>
							<td>
								Operation
							</td>
						</tr>
{#                        遍历数据库所有员工信息#}
                        {% for user in page.object_list %}
                            <tr class="row1">
                                <td>
{#                                    员工id#}
                                    {{ user.id }}
                                </td>
                                <td>
{#                                    员工姓名#}
                                    {{ user.name }}
                                </td>
                                <td>
{#                                    员工薪水#}
                                    {{ user.salary }}
                                </td>
                                <td>
{#                                    员工年龄#}
                                    {{ user.age }}
                                </td>
                                <td>
                                    <img src="{% static user.pic.url %}" alt="" width="50px" height="50px">
                                </td>
                                <td>
{#                                    a连接通过每人的id来进行删除或修改#}
{#                                    <a href="/hello/delete/?id={{ foo.id }}">delete emp</a>&nbsp;<a href="/hello/updateemp/?id={{ foo.id }} ">update emp</a>#}
{#                                    <a href="{% url 'loginapp:delete' %}?id={{ user.id }}">delete emp</a>&nbsp;<a href="{% url 'loginapp:updateemp' %}?id={{ user.id }} ">update emp</a>#}
                                    <a href="javascript:void(0)" onclick='deletedata({{ user.id }})'>delete emp</a>&nbsp;<a href="{% url 'loginapp:updateemp' %}?id={{ user.id }}&num={{ page.number }} ">update emp</a>
                                </td>
						    </tr>
                        {% endfor %}

					</table>

{#                    显示上一页#}
                    {% if page.has_previous %}
                        <a href="/hello/emplist/?num={{ page.previous_page_number }}">上一页</a>
                    {% endif %}

{#                    输出所有页号#}
                    {% for page_num in page.paginator.page_range %}
                        {% csrf_token %}
                        <a href="/hello/emplist/?num={{ page_num }}">
                            {% if num == page.number %}
                                <span class="a">{{ page_num }}</span>
                            {% else %}
                                <span class="b">{{ page_num }}</span>
                            {% endif %}
                        </a>
{#                        <a href='/hello/emplist/?num={{ page_num }}'>{{ page_num }}</a>#}
{#                        {{ page_num }}#}
                    {% endfor %}

                    {% if page.has_next %}
                        <a href="/hello/emplist/?num={{ page.next_page_number }}">下一页</a>
                    {% endif %}

					<p>
						<input type="button" class="button" value="Add Employee" onclick="location.href= '{% url "loginapp:addemp" %}?num={{ page.number}}'"/>

						<input type="button" class="button" value="Check" onclick="location.href='/hello/check'"/>
					</p>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>
	</body>
<script type="text/javascript">
    time=document.getElementById('time');
    date=new Date();
    time.innerHTML=date
</script>
</html>

project_emp/templates/ems/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>login</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css"
			href="/static/css/style.css" />
	</head>


	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="time">
{#								2012/12/05#}
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						login
					</h1>
{#					<form action="{% url loginapp:loginlogic %}" method="post">#}
					<form action="{% url 'loginapp:logincheck' %}" method="post">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0" class="form_table">
							<tr>
								<td valign="middle" align="right">
									username:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" id="name"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									password:
								</td>
								<td valign="middle" align="left">
                                    <input type="password" class="inputgri" id="pwd" />
								    <span id="text1"></span>
                                </td>
							</tr>
						</table>
						<p>
                            <input type="button" class="button" value="Regist" onclick="regist()">
							<input type="button" class="button" value="Submit &raquo;" onclick="check()" />
                            <input type="checkbox" name="checkbox" id ="remember"value="1">记住我
						</p>
					</form>

				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>

<script type="text/javascript">
    time=document.getElementById('time');
    date=new Date();
    time.innerHTML=date;

    function regist() {
       location.href="{% url 'loginapp:regist' %}"
    }

    function check(){
        name=document.getElementById('name').value;
        pwd=document.getElementById('pwd').value;
        checkbox=document.getElementById('remember').value;
        console.log(checkbox);
        var xhr;
        if (window.XMLHttpRequest){
            xhr=new XMLHttpRequest()
        }else if(window.ActiveXObject){
            xhr=new ActiveXObject('Microsoft.XMLHTTP')
        }
        xhr.open("post","{% url 'loginapp:logincheck' %}",true);
        xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        xhr.send("name="+name+"&pwd="+pwd+"&csrfmiddlewaretoken="+"{{ csrf_token }}");
        xhr.onreadystatechange=function () {
            if (xhr.readyState==4 && xhr.status==200){
{#                msgTag = document.getElementById("text1");#}
                if (xhr.responseText=='用户名或密码错误！'){
                    alert(xhr.responseText);
{#                    msgTag.innerHTML=xhr.responseText;#}
                }
                else if(xhr.responseText=='验证码错误！'){
                    alert(xhr.responseText);
                    location.href= "{% url 'loginapp:loginlogic'%}?name="+name+'&password='+pwd+'&checkbox='+checkbox;

                }
            }
        }
    }

</script>


</html>

project_emp/templates/ems/regist.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>regist</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="time">

{#								<br />#}
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						注册
					</h1>

					<form action="/hello/registlogic/" method="post" enctype="application/x-www-form-urlencoded">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="username" onblur="checkName();" id="input_name" />
                                    <img src="" alt="" id="id_img" width="20px" height="20px">
                                    <span id="msg"></span>
								</td>

							</tr>
							<tr>
								<td valign="middle" align="right">
									真实姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>

								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd1" onblur="checkpwd1()" id="pwd1"/>
								    <span id="spwd1"></span>
                                </td>
							</tr>
                            <tr>
								<td valign="middle" align="right">
									确认密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd2" onblur="checkpwd2()" id="'pwd2"/>
								    <span id="spwd2"></span>
                                </td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									性别:
								</td>
								<td valign="middle" align="left">
									男
									<input type="radio" class="inputgri" name="sex" value="男" checked="checked"/>
									女
									<input type="radio" class="inputgri" name="sex" value="女"/>
								</td>
							</tr>
							
							<tr>
								<td valign="middle" align="right">
									验证码:
									<img id ="num" src="{% url 'loginapp:getcaptcha' %}" style="height: 40px;width: 120px"/>
									<a href="javascript:void(0)" onclick=fun()>换一张</a>
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="number" onblur="captcha();" id="nerb"/>
                                    <span id="captcha"></span>
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Submit &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>


	</body>

<script type="text/javascript">

    time=document.getElementById('time');
    var date = new Date();
    time.innerHTML=date;

    function fun() {
        url=document.getElementById("num");
        url.src="{% url 'loginapp:getcaptcha' %}?"+new Date().getTime();

    }

    function checkName() {
        var imgl=document.getElementById('id_img');
        nameval=document.getElementById('input_name').value;
        var xhr;
        if (window.XMLHttpRequest){
            xhr=new XMLHttpRequest()
        }else if(window.ActiveXObject){
            xhr=new ActiveXObject('Microsoft.XMLHTTP')
        }

        xhr.open("post","{% url 'loginapp:user' %}",true);
        xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        xhr.send("name="+nameval+"&csrfmiddlewaretoken="+"{{ csrf_token }}");
        imgl.src='/static/images/5-121204193R5-50.gif';
        xhr.onreadystatechange=function () {
            if (xhr.readyState==4 && xhr.status==200){
                msgTag = document.getElementById("msg");
                msgTag.innerHTML=xhr.responseText;

                if (xhr.responseText=='用户名合法') {
                    imgl.src='/static/images/right_3.jpg'
                }else {
                    imgl.src='/static/images/error_3.jpg'
                }
            }
        }
    }

    function checkpwd1() {
        var pwd1=document.getElementById('pwd1');
        var spwd1=document.getElementById('spwd1');
        if (6<pwd1.value.length||pwd1.value.length<3){
            spwd1.innerHTML='请输入3-6位长度密码'
        }else{
            spwd1.innerHTML='密码有效'
        }
    }

    function checkpwd2() {
        var pwd1=document.getElementById('pwd1');
        var pwd2=document.getElementById('pwd2');
        var spwd1=document.getElementById('spwd1');
        var spwd2=document.getElementById('spwd2');
        if (pwd1.value==pwd2.value){
            spwd1.innerHTML='密码正确';
            spwd2.innerHTML='密码正确';
        }else {
            spwd1.innerHTML='两次密码输入不正确';
            spwd2.innerHTML='两次密码输入不正确';
        }
    }

    function captcha() {
        var num=document.getElementById('nerb').value;
        var xhr;
        if (window.XMLHttpRequest){
            xhr=new XMLHttpRequest()
        }else if(window.ActiveXObject){
            xhr=new ActiveXObject('Microsoft.XMLHTTP')
        }
        xhr.open("post","{% url 'loginapp:captchalogic' %}",true);
        xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        xhr.send("num="+num+"&csrfmiddlewaretoken="+"{{ csrf_token }}");
        xhr.onreadystatechange=function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                var cap = document.getElementById('captcha');
                cap.innerHTML = xhr.responseText;
            }
        }
    }

</script>

</html>